routes/web.php
<?php

use App\Http\Controllers\IndexController;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('/', 'IndexController');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


Route::namespace('Admin')->prefix('admin')->name('admin.')->middleware('can:manage-users')->group(function() {
    Route::get('', 'AdminController@index')->name('index');
    Route::get('lang/{lang}',['as'=>'lang', 'uses'=>'LangController@changeLang']);

    Route::resource('users', 'UserController', ['except' => ['show']])->middleware('can:manage-organization');

    Route::resource('organization', 'OrganizationController', ['except' => ['show']])->middleware('can:manage-organization');

    Route::resource('category', 'CategoryController', ['except' => ['show']])->middleware('can:access_useradmin');

    Route::resource('level', 'LevelController', ['except' => ['show']])->middleware('can:access_useradmin');

    Route::resource('program', 'ProgramController', ['except' => ['show']]);

    Route::resource('logo', 'LogoController');
});

app/Logo.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Logo extends Model
{
    protected $table="logo";
}

app/Http/Controllers/Admin/LogoController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Logo;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;

class LogoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $logos = Logo::paginate(10);
        return view('admin.logo.index')->with(['logos' => $logos]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.logo.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if($request->hasFile('logo')) {
            $filenameWithExt = $request->file('logo')->getClientOriginalName();
            $filename = pathinfo($filenameWithExt, PATHINFO_FILENAME);
            $extension = $request->file('logo')->getClientOriginalExtension();
            $fileNameToStore = $filename."_".time().".".$extension;
            $path = $request->file('logo')->storeAs('public/logomaster',$fileNameToStore);
        }else {
            $fileNameToStore = 'noimage.jpg';
        }

        $logo = new Logo;
        $logo->name = $request->name;
        $logo->logo = $fileNameToStore;

        $logo->save();

        return redirect()->route('admin.logo.create')->with('messenger','Create Success');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Logo  $logo
     * @return \Illuminate\Http\Response
     */
    public function show(Logo $logo)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Logo  $logo
     * @return \Illuminate\Http\Response
     */
    public function edit(Logo $logo)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Logo  $logo
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Logo $logo)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Logo  $logo
     * @return \Illuminate\Http\Response
     */
    public function destroy(Logo $logo)
    {
        //
    }
}

resources/views/admin/logo/create.blade.php
@extends('admin.layouts_admin.index')

@section('content')
<div class="container">
    @if(session('messenger'))
        <div class="alert alert-success" role="alert">
            {{session('messenger')}}
        </div>
    @endif
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header d-flex">
                    <h4>Create Logo</h4>
                    <a href="{{ route('admin.logo.index') }}" class="ml-auto">Back</a>
                </div>
                <div class="card-body">
                    <form action="{{ route('admin.logo.store') }}" method="post" enctype="multipart/form-data">
                    @csrf
                        <div class="form-group">
                            <label>Name</label>
                            <input type="text" class="form-control" id="name" name="name" placeholder="Please Enter Username" value="{{ old('name') }}">
                            @if($errors->has('name'))
                                <small class="form-text text-muted">{{$errors->first('name')}}</small>
                            @endif
                        </div>
                        <div class="form-group">
                            <label>Logo</label>
                            <input type="file" id="photo" name="logo"  value="" class="form-control">
                            @if($errors->has('logo'))
                                <small  class="form-text text-muted">{{$errors->first('logo')}}</small>
                            @endif
                        </div>
                        <button type="submit" class="btn btn-primary">Create</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    $(document).ready(function(){
        $("li.slide-list >ul:last").slideDown();
        $("li.slide-list >ul:last li:last").addClass("active");
    });
</script>
@endsection

resources/views/admin/logo/edit.blade.php
@extends('admin.layouts_admin.index')

@section('content')
<div class="container">
    @if(session('messenger'))
        <div class="alert alert-success" role="alert">
            {{session('messenger')}}
        </div>
    @endif
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header d-flex">
                    <h4>Edit Organization: {{$organization->name}}</h4>
                    <a href="{{ route('admin.organization.index') }}" class="ml-auto">Back</a>
                </div>
                <div class="card-body">
                    <form action="{{ route('admin.organization.update', $organization) }}" method="post" enctype="multipart/form-data">
                    @csrf
                    {{method_field('PUT')}}
                        <div class="form-group">
                            <label>Name</label>
                            <input type="text" class="form-control" id="name" name="name" placeholder="Please Enter Username" value="{{ $organization->name }}"
                            @if(Gate::denies('access_users')) readonly @endif>
                            @if($errors->has('name'))
                                <small class="form-text text-muted">{{$errors->first('name')}}</small>
                            @endif
                        </div>
                        <div class="form-group">
                            <label>Logo</label>
                            <input type="file" id="photo" name="logo"  value="" class="form-control">
                            @if($errors->has('logo'))
                                <small  class="form-text text-muted">{{$errors->first('logo')}}</small>
                            @endif
                        </div>
                        <div class="form-group">
                            <label>Foundation Year</label>
                            <input class="form-control" type="date" name="create_at" id=""  value="{{ $organization->foundation_year }}" >
                            @if($errors->has('create_at'))
                                <small  class="form-text text-muted">{{$errors->first('create_at')}}</small>
                            @endif
                        </div>
                        <div class="form-group">
                            <label>Address</label>
                            <input type="text" class="form-control" name="address" id="" placeholder="Please Enter Address" value="{{ $organization->address }}">
                            @if($errors->has('address'))
                                <small  class="form-text text-muted">{{$errors->first('address')}}</small>
                            @endif
                        </div>
                        <div class="form-group">
                            <label>Description</label>
                            <textarea name="description" id="des" cols="22" rows="3" class="form-control" >{{ $organization->description }}</textarea>
                            @if($errors->has('description'))
                                <small class="form-text text-muted">{{$errors->first('description')}}</small>
                            @endif
                        </div>
                        <div class="from-group">
                            <label>Ulr</label>
                            <input type="text" class="form-control" name="url" id="" placeholder="Please Enter Ulr" value="{{ $organization->url }}">
                            @if($errors->has('url'))
                                <small  class="form-text text-muted">{{$errors->first('url')}}</small>
                            @endif
                        </div>
                        <button type="submit" class="btn btn-primary">Update</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/logo/index.blade.php
@extends('admin.layouts_admin.index')

@section('content')
<div class="container">
    @if(session('messenger'))
        <div class="alert alert-success" role="alert">
            {{session('messenger')}}
        </div>
    @endif
    <!-- <div class="row justify-content-center"> -->
        <!-- <div class="col-md-8"> -->
            <div class="card">
                <div class="card-header d-flex">
                    <h4>Logo</h4>
                    {{-- @can('access_users') --}}
                    <a href="{{ route('admin.logo.create') }}" class="ml-auto"><button type="button" class="btn btn-success">Create Logo</button></a>
                    {{-- @endcan --}}
                </div>


                <div class="card-body">
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Name</th>
                            <th scope="col">Logo</th>
                            <th scope="col">Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($logos as $logo)
                        <tr>
                            <th scope="row">{{$logo->id}}</th>
                            <td>{{ $logo->name }}</td>
                            <td><img style="width:100%;" src="http://127.0.0.1/boookshop/public/storage/logomaster/{{$logo->logo}}" alt=""></td>
                            <td class="d-flex">
                                <a href="{{ route('admin.logo.edit', $logo->id) }}"><button type="button" class="btn btn-primary">Edit</button></a>
                                {{-- @can('access_users') --}}
                                <form action="{{ route('admin.logo.destroy', $logo) }}" method="post">
                                @csrf
                                    {{method_field('DELETE')}}
                                    <button type="submit" class="btn btn-warning">Delete</button>
                                </form>
                                {{-- @endcan --}}
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
                @can('access_users')
                {{$logos->links()}}
                @endcan
                </div>
            </div>
        <!-- </div> -->
    <!-- </div> -->
</div>
<script>
    $(document).ready(function(){
        $("li.slide-list >ul:last").slideDown();
        $("li.slide-list >ul:last li:first").addClass("active");
    });
</script>
@endsection