routes/web.php
<?php

use App\Http\Controllers\IndexController;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('/', 'IndexController');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


Route::namespace('Admin')->prefix('admin')->name('admin.')->middleware('can:manage-users')->group(function() {
    Route::get('', 'AdminController@index')->name('index');
    Route::get('lang/{lang}',['as'=>'lang', 'uses'=>'LangController@changeLang']);

    Route::resource('users', 'UserController', ['except' => ['show']])->middleware('can:manage-organization');

    Route::resource('organization', 'OrganizationController', ['except' => ['show']])->middleware('can:manage-organization');

    Route::resource('category', 'CategoryController', ['except' => ['show']])->middleware('can:access_useradmin');

    Route::resource('level', 'LevelController', ['except' => ['show']])->middleware('can:access_useradmin');

    Route::resource('program', 'ProgramController', ['except' => ['show']]);

    Route::resource('logo', 'LogoController');
});

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    protected $table="users";
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function relation_organization() {
        return $this->belongsTo('App\Organization', 'organization');
        // return $this->belongsTo(Organization::class, 'organization');
    }

    public function programs() {
        return $this->hasMany('App\Program');
    }

    public function roles() {
        return $this->belongsToMany('App\Role');
    }

    public function hasAnyRoles($roles) {
        if($this->roles()->whereIn('name', $roles)->first()) {
            return true;
        }else {
            return false;
        }
    }
    public function hasRole($role) {
        if($this->roles()->where('name', $role)->first()) {
            return true;
        }else {
            return false;
        }
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\User;
use App\Organization;
use App\Role;
use App\Http\Requests\UserCreateRequest;
use App\Http\Requests\UserEditRequest;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Gate;
use Illuminate\Auth\Access\Gate as AccessGate;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class UserController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index() {
        if(Gate::allows('access_useradmin')) {
            $users = User::paginate(10);
        }else {
            $current_organization = Auth::user()->organization;
            $users = User::where('organization', '=', $current_organization)->paginate(10);
        }

        // return view('admin.users.index', ['users' => $users]);
        return view('admin.users.index')->with(['users' => $users]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if(Gate::allows('access_useradmin')) {
            $organizations = Organization::all();
            $roles = Role::all();
        } else {
            $current_organization = Auth::user()->organization;
            $organizations = Organization::where('id', '=', $current_organization)->get();
            // $current_role = Auth::user()->id;
            // $roles = User::find($current_role)->roles()->get();
            $roles = Role::where('id', '=', 3)->get();
            // $roles = $current_role->find(3);

        }
        // dd($current_role);
        return view('admin.users.create')->with([
            'organizations' => $organizations,
            'roles' => $roles
            ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(UserCreateRequest $request)
    {
        if($request->hasFile('thumb')) {
            $filenameWithExt = $request->file('thumb')->getClientOriginalName();
            $filename = pathinfo($filenameWithExt, PATHINFO_FILENAME);
            $extension = $request->file('thumb')->getClientOriginalExtension();
            $fileNameToStore = $filename."_".time().".".$extension;
            $path = $request->file('thumb')->storeAs('public/thumbs',$fileNameToStore);
        }else {
            $fileNameToStore = 'noimage.jpg';
        }

        $user = new User;

        $user->name = $request ->name;
        $user->password = bcrypt($request ->password);
        $user->email = $request ->email;
        $user->first_name = $request->first_name;
        $user->last_name = $request->last_name;
        $user->gender = $request->gender;
        $user->phone = $request->phone;
        $user->thumb =  $fileNameToStore;
        $user->description = $request->description;
        $user->organization = $request->organization;
        $user->active = $request->active;

        $user->save();

        $user->roles()->sync($request->role);
        return redirect()->route('admin.users.create')->with('messenger', 'Create Success');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        // if(Gate::denies('edit_users')) {
        //     return redirect()->route('admin.users.index')->with('messenger','Not Access');
        // }
        $roles = Role::all();
        $organizations = Organization::all();
        return view('admin.users.edit')->with([
            'user' => $user,
            'organizations' => $organizations,
            'roles' =>$roles
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(UserEditRequest $request, User $user)
    {
        if($request->hasFile('thumb')) {
            $filenameWithExt = $request->file('thumb')->getClientOriginalName();
            $filename = pathinfo($filenameWithExt, PATHINFO_FILENAME);
            $extension = $request->file('thumb')->getClientOriginalExtension();
            $fileNameToStore = $filename."_".time().".".$extension;
            $path = $request->file('thumb')->storeAs('public/thumbs',$fileNameToStore);
        }

        $user->roles()->sync($request->role);
        $user->name = $request ->name;
        if(isset($request ->password)){
            $user ->password = bcrypt($request ->password);
        }
        $user->email = $request ->email;
        $user->first_name = $request->first_name;
        $user->last_name = $request->last_name;
        $user->gender = $request->gender;
        $user->phone = $request->phone;
        if($request->hasFile('thumb')) {
            $user->thumb = $fileNameToStore;
        }
        $user->description = $request->description;
        $user->organization = $request->organization;
        $user->active = $request->active;
        if(isset($request ->password)){
            $user ->password = bcrypt($request ->password);
        }

        $user ->save();



        return redirect()->route('admin.users.index')->with('messenger', 'Update Success');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        // if(Gate::denies('delete_users')) {
        //     return redirect()->route('admin.users.index')->with('messenger','Not Access');
        // }
        if($user->thumb != "noimage.jpg"){
            Storage::delete('public/thumbs/'.$user->thumb);
        }
        $user->roles()->detach();
        $user->delete();

        return redirect()->route('admin.users.index')->with('messenger', 'Delete Success');
    }
}

resources/views/admin/users/create.blade.php
@extends('admin.layouts_admin.index')

@section('content')
{{-- <div class="container"> --}}
    @if(session('messenger'))
        <div class="alert alert-success" role="alert">
            {{session('messenger')}}
        </div>
    @endif
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header d-flex">
                    <h4>Create User</h4>
                    <a href="{{ route('admin.users.index') }}" class="ml-auto">Back</a>
                </div>
                <div class="card-body">
                    <form action="{{ route('admin.users.store') }}" method="post" enctype="multipart/form-data">
                    @csrf
                        <div class="form-group">
                            <label>Username</label>
                            <input type="text" class="form-control" id="name" name="name" placeholder="Please Enter Username" value="{{ old('name') }}">
                            @if($errors->has('name'))
                                <small id="emailHelp" class="form-text text-muted">{{$errors->first('name')}}</small>
                            @endif
                        </div>
                        <div class="form-group">
                            <label>First Name</label>
                            <input type="text" class="form-control" name="first_name" id="" placeholder="Please Enter First Name" value="{{ old('first_name') }}">
                            @if($errors->has('first_name'))
                                <small id="emailHelp" class="form-text text-muted">{{$errors->first('first_name')}}</small>
                            @endif
                        </div>
                        <div class="form-group">
                            <label>Last Name</label>
                            <input type="text" class="form-control" name="last_name" id="" placeholder="Please Enter Last Name" value="{{ old('last_name') }}">
                            @if($errors->has('last_name'))
                                <small id="emailHelp" class="form-text text-muted">{{$errors->first('last_name')}}</small>
                            @endif
                        </div>
                        <div class="form-group">
                            <label>Gender: </label>
                            <input type="radio" class="" name="gender" id="" value="male">
                            <label>Male</label>
                            <input type="radio" class="" name="gender" id="" value="female">
                            <label>Female</label>
                            <input type="radio" class="" name="gender" id="" value="other">
                            <label>Other</label>
                            @if($errors->has('gender'))
                                <small id="emailHelp" class="form-text text-muted">{{$errors->first('gender')}}</small>
                            @endif
                        </div>
                        <div class="form-group">
                            <label>Email</label>
                            <input class="no_drop form-control" type="email" name="email" id="" placeholder="Please Enter Email" value="{{ old('email') }}" >
                            @if($errors->has('email'))
                                <small id="emailHelp" class="form-text text-muted">{{$errors->first('email')}}</small>
                            @endif
                        </div>
                        <div class="form-group">
                            <label>Phone Number</label>
                            <input type="text" class="form-control" name="phone" id="" placeholder="Please Enter Phone Number" value="{{ old('phone') }}">
                            @if($errors->has('phone'))
                                <small id="emailHelp" class="form-text text-muted">{{$errors->first('phone')}}</small>
                            @endif
                        </div>
                        <div class="form-group">
                            <label>Thumb</label>
                            <input type="file" id="photo" name="thumb"  value="" class="form-control">
                            @if($errors->has('thumb'))
                                <small  class="form-text text-muted">{{$errors->first('thumb')}}</small>
                            @endif
                        </div>
                        <div class="form-group">
                            <label>Description</label>
                            <textarea name="description" id="des" cols="22" rows="3" class="form-control" >{{ old('description') }}</textarea>
                            @if($errors->has('description'))
                                <small id="emailHelp" class="form-text text-muted">{{$errors->first('description')}}</small>
                            @endif
                        </div>
                        <div class="form-group">
                            <label>Organization</label>
                            <select name="organization" id="organization" class="custom-select">
                                <option selected>Choose...</option>
                                @foreach($organizations as $organization)
                                <option value="{{$organization->id}}">{{$organization->name}}</option>
                                @endforeach
                            </select>
                            @if($errors->has('organization'))
                                <small id="emailHelp" class="form-text text-muted">{{$errors->first('organization')}}</small>
                            @endif
                        </div>
                        <div class="form-group">
                            <label>Active: </label>
                            <input type="radio" class="" name="active" id="" value="yes">
                            <label>Yes</label>
                            <input type="radio" class="" name="active" id="" value="no">
                            <label>No</label>
                            @if($errors->has('active'))
                                <small id="emailHelp" class="form-text text-muted">{{$errors->first('active')}}</small>
                            @endif
                        </div>
                        {{-- @can('access_useradmin') --}}
                        <div class="form-group">
                            <label>Role: </label>
                            @foreach($roles as $role)
                            <input type="radio" class="" name="role" id="" value="{{$role->id}}">
                            <label>{{$role->name}}</label>
                            @endforeach
                            @if($errors->has('role'))
                                <small id="emailHelp" class="form-text text-muted">{{$errors->first('role')}}</small>
                            @endif
                        </div>
                        {{-- @endcan --}}
                        <div class="form-group">
                            <label>Password</label>
                            <input type="password" class="form-control" name="password" id="" placeholder="Please Enter Password" value="">
                            @if($errors->has('password'))
                                <small id="emailHelp" class="form-text text-muted">{{$errors->first('password')}}</small>
                            @endif
                        </div>
                        <div class="form-group">
                            <label>RePassword</label>
                            <input type="password" class="form-control" name="repassword" id="" placeholder="Please Enter RePassword">
                            @if($errors->has('repassword'))
                                <small id="emailHelp" class="form-text text-muted">{{$errors->first('repassword')}}</small>
                            @endif
                        </div>
                        <button type="submit" class="btn btn-primary">Create</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{{-- </div> --}}
<script>
    $(document).ready(function(){
        $("li.user-list >ul:last").slideDown();
        $("li.user-list >ul:last li:last").addClass("active");
    });
</script>
@endsection

resources/views/admin/users/edit.blade.php
@extends('admin.layouts_admin.index')

@section('content')
{{-- <div class="container"> --}}
    @if(session('messenger'))
        <div class="alert alert-success" role="alert">
            {{session('messenger')}}
        </div>
    @endif
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header d-flex">
                    <h4>Edit User: {{$user->name}}</h4>
                    <a href="{{ route('admin.users.index') }}" class="ml-auto">Back</a>
                </div>
                <div class="card-body">
                    <form action="{{ route('admin.users.update', $user) }}" method="post" enctype="multipart/form-data">
                    @csrf
                    {{method_field('PUT')}}
                        <div class="form-group">
                            <label>Username</label>
                            <input type="text" class="form-control" id="name" name="name" placeholder="Please Enter Username" value="{{ $user->name }}">
                            @if($errors->has('name'))
                                <small id="emailHelp" class="form-text text-muted">{{$errors->first('name')}}</small>
                            @endif
                        </div>
                        <div class="form-group">
                            <label>First Name</label>
                            <input type="text" class="form-control" name="first_name" id="" placeholder="Please Enter First Name" value="{{ $user->first_name }}">
                            @if($errors->has('first_name'))
                                <small id="emailHelp" class="form-text text-muted">{{$errors->first('first_name')}}</small>
                            @endif
                        </div>
                        <div class="form-group">
                            <label>Last Name</label>
                            <input type="text" class="form-control" name="last_name" id="" placeholder="Please Enter Last Name" value="{{ $user->last_name }}">
                            @if($errors->has('last_name'))
                                <small id="emailHelp" class="form-text text-muted">{{$errors->first('last_name')}}</small>
                            @endif
                        </div>
                        <div class="form-group">
                            <label>Gender: </label>
                            <input type="radio" class="" name="gender" id="" value="male" @if($user->gender == 'male') checked @endif>
                            <label>Male</label>
                            <input type="radio" class="" name="gender" id="" value="female"@if($user->gender == 'female') checked @endif>
                            <label>Female</label>
                            <input type="radio" class="" name="gender" id="" value="other"@if($user->gender == 'other') checked @endif>
                            <label>Other</label>
                            @if($errors->has('gender'))
                                <small id="emailHelp" class="form-text text-muted">{{$errors->first('gender')}}</small>
                            @endif
                        </div>
                        <div class="form-group">
                            <label>Email</label>
                            <input class="no_drop form-control" type="email" name="email" id="" placeholder="Please Enter Email" value="{{ $user->email }}" >
                            @if($errors->has('email'))
                                <small id="emailHelp" class="form-text text-muted">{{$errors->first('email')}}</small>
                            @endif
                        </div>
                        <div class="form-group">
                            <label>Phone Number</label>
                            <input type="text" class="form-control" name="phone" id="" placeholder="Please Enter Phone Number" value="{{ $user->phone }}">
                            @if($errors->has('phone'))
                                <small id="emailHelp" class="form-text text-muted">{{$errors->first('phone')}}</small>
                            @endif
                        </div>
                        <div class="form-group">
                            <label>Thumb</label>
                            <input type="file" id="photo" name="thumb"  value="" class="form-control">
                            @if($errors->has('thumb'))
                                <small  class="form-text text-muted">{{$errors->first('thumb')}}</small>
                            @endif
                        </div>
                        <div class="form-group">
                            <label>Description</label>
                            <textarea name="description" id="des" cols="22" rows="3" class="form-control" >{{ $user->description }}</textarea>
                            @if($errors->has('description'))
                                <small id="emailHelp" class="form-text text-muted">{{$errors->first('description')}}</small>
                            @endif
                        </div>
                        <div class="form-group">
                            <label>Organization</label>
                            <select name="organization" id="organization" class="custom-select">
                                <option selected>Choose...</option>
                                @foreach($organizations as $organization)
                                <option value="{{$organization->id}}">{{$organization->name}}</option>
                                @endforeach
                            </select>
                            @if($errors->has('organization'))
                                <small id="emailHelp" class="form-text text-muted">{{$errors->first('organization')}}</small>
                            @endif
                        </div>
                        <div class="form-group">
                            <label>Active: </label>
                            <input type="radio" class="" name="active" id="" value="yes" @if($user->active == 'yes') checked @endif>
                            <label>Yes</label>
                            <input type="radio" class="" name="active" id="" value="no" @if($user->active == 'no') checked @endif>
                            <label>No</label>
                            @if($errors->has('active'))
                                <small id="emailHelp" class="form-text text-muted">{{$errors->first('active')}}</small>
                            @endif
                        </div>
                        <div class="form-group">
                            <label>Role: </label>
                            @foreach($roles as $role)
                            <input type="radio" class="" name="role[]" id="" value="{{$role->id}}">
                            <label>{{$role->name}}</label>
                            @endforeach
                            @if($errors->has('role'))
                                <small id="emailHelp" class="form-text text-muted">{{$errors->first('role')}}</small>
                            @endif
                        </div>
                        <div class="form-group">
                            <label>Password</label>
                            <input type="password" class="form-control" name="password" id="" placeholder="Please Enter Password" value="">
                            @if($errors->has('password'))
                                <small id="emailHelp" class="form-text text-muted">{{$errors->first('password')}}</small>
                            @endif
                        </div>
                        <div class="form-group">
                            <label>RePassword</label>
                            <input type="password" class="form-control" name="repassword" id="" placeholder="Please Enter RePassword">
                            @if($errors->has('repasswprd'))
                                <small id="emailHelp" class="form-text text-muted">{{$errors->first('repasswprd')}}</small>
                            @endif
                        </div>
                        <button type="submit" class="btn btn-primary">Update</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{{-- </div> --}}
@endsection

resources/views/admin/users/index.blade.php
@extends('admin.layouts_admin.index')

@section('content')
{{-- <div class="container"> --}}
    @if(session('messenger'))
        <div class="alert alert-success" role="alert">
            {{session('messenger')}}
        </div>
    @endif
    <!-- <div class="row justify-content-center">
        <div class="col-md-8"> -->
            <div class="card">
                <div class="card-header d-flex">
                    <h4>List User</h4>
                    {{-- <a href="{{ route('admin.users.create') }}" class="ml-auto"><button type="button" class="btn btn-success">Create User Manager</button></a> --}}
                </div>
                <div class="card-body">
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Name</th>
                            <th scope="col">Email</th>
                            <th scope="col">Role</th>
                            <th scope="col">First Name</th>
                            <th scope="col">Last Name</th>
                            <th scope="col">Gender</th>
                            <th scope="col">Phone Number</th>
                            <th scope="col">Thumb</th>
                            <th scope="col">Description</th>
                            <th scope="col">Organization</th>
                            <th scope="col">Active</th>
                            <th scope="col">Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($users as $user)
                        <tr>
                            <th scope="row">{{$user->id}}</th>
                            <td>{{ $user->name }}</td>
                            <td>{{ $user->email }}</td>
                            <td>{{ implode($user->roles()->get()->pluck('name')->toArray()) }}</td>
                            <td>{{ $user->first_name }}</td>
                            <td>{{ $user->last_name }}</td>
                            <td>{{ $user->gender }}</td>
                            <td>{{ $user->phone }}</td>
                            <td><img style="width:100%;" src="http://127.0.0.1/boookshop/public/storage/thumbs/{{$user->thumb}}" alt=""></td>
                            <td>{{ $user->description }}</td>
                            <td>{{ @$user->relation_organization->name }}</td>
                            <td>{{ $user->active }}</td>
                            <td class="d-flex">
                                <a href="{{ route('admin.users.edit', $user->id) }}"><button type="button" class="btn btn-primary">Edit</button></a>
                                <form action="{{ route('admin.users.destroy', $user) }}" method="post">
                                @csrf
                                    {{method_field('DELETE')}}
                                    <button type="submit" class="btn btn-warning">Delete</button>
                                </form>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
                {{$users->links()}}
                </div>
            </div>
        <!-- </div>
    </div> -->
{{-- </div> --}}
<script>
    $(document).ready(function(){
        $("li.user-list >ul:last").slideDown();
        $("li.user-list >ul:last li:first").addClass("active");
    });
</script>
@endsection