routes/web.php
<?php

use App\Http\Controllers\IndexController;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('/', 'IndexController');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


Route::namespace('Admin')->prefix('admin')->name('admin.')->middleware('can:manage-users')->group(function() {
    Route::get('', 'AdminController@index')->name('index');
    Route::get('lang/{lang}',['as'=>'lang', 'uses'=>'LangController@changeLang']);

    Route::resource('users', 'UserController', ['except' => ['show']])->middleware('can:manage-organization');

    Route::resource('organization', 'OrganizationController', ['except' => ['show']])->middleware('can:manage-organization');

    Route::resource('category', 'CategoryController', ['except' => ['show']])->middleware('can:access_useradmin');

    Route::resource('level', 'LevelController', ['except' => ['show']])->middleware('can:access_useradmin');

    Route::resource('program', 'ProgramController', ['except' => ['show']]);

    Route::resource('logo', 'LogoController');
});

resources/views/admin/layouts_admin/header.blade.php
<div class="navbar navbar-expand-sm bg-light navbar-light d-flex justify-content-between header">
    <a href="#" class="navbar-brand " ><h2>{{ __('invariable_admin.header.admin')}}</h2></a>
    <div class="d-flex">
        <div class="leguage">
            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">
                <!-- <i class="fas fa-user"></i> -->
            </a>
            <div class="dropdown-menu ">
                <a class="dropdown-item" href="{{ route('admin.lang', ['lang' =>'en']) }}"><i class="fas fa-user"></i> EN</a>
                <a class="dropdown-item" href="{{ route('admin.lang', ['lang' =>'vi']) }}"><i class="fas fa-cog"></i> VI</a>
            </div>
        </div>
        <div>
            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">
                <!-- <i class="fas fa-user"></i>  -->
                {{  Auth::user()->name }}
            </a>
            <div class="dropdown-menu dropdown-user">
                <!-- <a class="dropdown-item" href="#"><i class="fas fa-user"></i> {{  Auth::user()->name }}</a> -->
                <a class="dropdown-item" href="#"><i class="fas fa-cog"></i> {{ __('invariable_admin.header.setting_user')}}</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{{ route('logout')}}" onclick="event.preventDefault();
                document.getElementById('logout-form').submit();">
                    <i class="fas fa-sign-out-alt"></i>
                    {{ __('invariable_admin.header.login_user')}}
                    </a>
                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                    @csrf
                </form>
            </div>
        </div>

    </div>

</div>

resources/views/admin/layouts_admin/index.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin</title>
    <!-- Latest compiled and minified CSS -->
    {{-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"> --}}

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Admin') }}</title>
    <link rel="icon" type="image/png" href="http://127.0.0.1/boookshop/public/image/favicon-32x32.png">

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- CSS  -->
    {{-- <link rel="stylesheet" href="{{asset('css/dist/admin/general_admin.css')}}"> --}}
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="{{asset('css/admin/header_admin.css')}}">
    <link rel="stylesheet" href="{{asset('css/admin/menu_admin.css')}}">
    {{-- <link rel="stylesheet" href="{{asset('css/dist/admin/main_list_admin.css')}}"> --}}
    {{-- <link rel="stylesheet" href="{{asset('css/dist/admin/main_create_edit_admin.css')}}"> --}}



    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <!-- Popper JS -->
    {{-- <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script> --}}

    <!-- Latest compiled JavaScript -->
    {{-- <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script> --}}

    <!-- Font Awesome's -->
    {{-- <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.13.0/css/all.css" integrity="sha384-Bfad6CLCknfcloXFOyFnlgtENryhrpZCe29RTifKEixXQZ38WheV+i/6YWSzkz3V" crossorigin="anonymous"> --}}
</head>
<body>
    <div>
        <div class="header-main">
            @include('admin.layouts_admin.header')
        </div>
        <div class="main">
            <div class="main-left">
                @include('admin.layouts_admin.menu')
            </div>
            <div class="main-right">
                @yield('content')
            </div>
        </div>

    </div>

    <script>
        $(document).ready(function(){
            $("li.list-menu-bottom").click(function(){
            //  $(this).find('span:fist').toggleClass('fas fa-chevron-down');
                var currentUl = $(this).find('ul');

                $("li.list-menu-bottom > ul").each(function() {
                    if($(this).is(currentUl)) {
                        $(this).slideToggle();
                    }else {
                        $(this).slideUp();
                    }
                });
            });
        });
    </script>


</body>
</html>

resources/views/admin/layouts_admin/menu.blade.php
<div class="menu">
    <ul class="nav flex-column" id="side-menu">
        <li class="list-menu-bottom">
            <a href="#">
                <i class="fas fa-tachometer-alt"></i>
                {{ __('invariable_admin.menu.dasboard')}}
            </a>
        </li>
        @can('manage-organization')
        <li class="list-menu-bottom user-list">
            <a href="#">
                <i class="fas fa-users"></i>
                {{ __('invariable_admin.menu.user')}}
                <!-- <span class="fas fa-chevron-left arrow"></span> -->
                <span class="fas fa-chevron-down arrow"></span>
            </a>
            <ul class="list-menu-top ">
                <li>
                    <a href="{{ route('admin.users.index')}}">{{ __('invariable_admin.menu.list_user')}}</a>
                </li>
                <li>
                    <a href="{{ route('admin.users.create')}}">{{ __('invariable_admin.menu.add_user')}}</a>
                </li>
            </ul>
        </li>
        <li class="list-menu-bottom organization-list">
            <a href="#" ><i class="fas fa-list-alt"></i>
            {{ __('invariable_admin.menu.organization')}}
                <!-- <span class="fas fa-chevron-left arrow"></span> -->
                <span class="fas fa-chevron-down arrow"></span>
            </a>
            <ul class="list-menu-top ">
                <li>
                    <a href="{{ route('admin.organization.index') }}">{{ __('invariable_admin.menu.list_organization')}}</a>
                </li>
                <li>
                    <a href="{{ route('admin.organization.create') }}">{{ __('invariable_admin.menu.add_organization')}}</a>
                </li>
            </ul>
        </li>
        @endcan
        @can('access_useradmin')
        <li class="list-menu-bottom category-list">
            <a href="#" ><i class="fas fa-list-alt"></i>
            {{ __('invariable_admin.menu.category')}}
                <!-- <span class="fas fa-chevron-left arrow"></span> -->
                <span class="fas fa-chevron-down arrow"></span>
            </a>
            <ul class="list-menu-top ">
                <li>
                    <a href="{{ route('admin.category.index') }}">{{ __('invariable_admin.menu.list_category')}}</a>
                </li>
                <li>
                    <a href="{{ route('admin.category.create') }}">{{ __('invariable_admin.menu.add_category')}}</a>
                </li>
            </ul>
        </li>
        @endcan
        @can('access_useradmin')
        <li class="list-menu-bottom level-list">
            <a href="#" ><i class="fas fa-list-alt"></i>
            {{ __('invariable_admin.menu.level')}}
                <!-- <span class="fas fa-chevron-left arrow"></span> -->
                <span class="fas fa-chevron-down arrow"></span>
            </a>
            <ul class="list-menu-top ">
                <li>
                    <a href="{{ route('admin.level.index') }}">{{ __('invariable_admin.menu.list_level')}}</a>
                </li>
                <li>
                    <a href="{{ route('admin.level.create') }}">{{ __('invariable_admin.menu.add_level')}}</a>
                </li>
            </ul>
        </li>
        @endcan
        <li class="list-menu-bottom program-list">
            <a href="#" ><i class="fas fa-cube"></i>
            {{ __('invariable_admin.menu.program')}}
                <!-- <span class="fas fa-chevron-left arrow"></span> -->
                <span class="fas fa-chevron-down arrow"></span>
            </a>
            <ul class="list-menu-top ">
                <li>
                    <a href="{{ route('admin.program.index')}}">{{ __('invariable_admin.menu.list_program')}}</a>
                </li>
                @can('create_programs')
                <li>
                    <a href="{{ route('admin.program.create')}}">{{ __('invariable_admin.menu.add_program')}}</a>
                </li>
                @endcan
            </ul>
        </li>
        {{-- <li class="list-menu-bottom bill-list">
            <a href="#" ><i class="fas fa-file-invoice-dollar"></i>
            {{ __('invariable_admin.menu.bill')}}
                <!-- <span class="fas fa-chevron-left arrow"></span> -->
                <!-- <span class="fas fa-chevron-down arrow"></span> -->
            </a>
        </li> --}}
        {{-- <li class="list-menu-bottom news-list">
            <a href="#" ><i class="fas fa-newspaper"></i>
            {{ __('invariable_admin.menu.news')}}
                <!-- <span class="fas fa-chevron-left arrow"></span> -->
                <span class="fas fa-chevron-down arrow"></span>
            </a>
            <ul class="list-menu-top ">
                <li>
                    <a href="#">{{ __('invariable_admin.menu.list_news')}}</a>
                </li>
                <li>
                    <a href="#">{{ __('invariable_admin.menu.add_news')}}</a>
                </li>
            </ul>
        </li> --}}
        @can('access_useradmin')
        <li class="list-menu-bottom slide-list">
            <a href="#" ><i class="fas fa-images"></i>
            {{ __('invariable_admin.menu.image')}}
                <!-- <span class="fas fa-chevron-left arrow"></span> -->
                <span class="fas fa-chevron-down arrow"></span>
            </a>
            <ul class="list-menu-top ">
                <li>
                    <a href="{{ route('admin.logo.index')}}">{{ __('invariable_admin.menu.list_image')}}</a>
                </li>
                <li>
                    <a href="{{ route('admin.logo.create')}}">{{ __('invariable_admin.menu.add_image')}}</a>
                </li>
            </ul>
        </li>
        @endcan
    </ul>
</div>